version: '3.8'

services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BASE_URL=${BASE_URL:-http://localhost:8080}
    container_name: VPS-2-FE
    image: sebastiankociuba/node-frontend:latest
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - BASE_URL=${BASE_URL:-http://localhost:8080}
    restart: always
